config/routes.rb
# frozen_string_literal: true

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => "/sidekiq"
  use_doorkeeper do
    skip_controllers :authorizations, :applications,
                     :authorized_applications
  end
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      get 'products/discarded', to: 'products#discarded'
      resources :products, except: %i[new edit] do
        put 'like', to: 'products#like'
        put 'dislike', to: 'products#dislike'
      end
      resources :orders, only: %i[index show]
      resources :carts, only: [:index], path: 'cart'
      resource :carts, except: %i[new edit show update] do
        put 'finalize', to: 'carts#finalize'
        put 'merge', to: 'carts#merge'
        patch 'discontinue', to: 'carts#discontinue'
        put 'update_line', to: 'carts#update_line'
        put 'delete_line', to: 'carts#delete_line'
      end
      resources :users, only: %i[index show]
      post 'users/password', to: 'passwords#create'
      put 'users/password', to: 'passwords#update'
    end
  end
  root to: 'products#index'
  resources :billing, only: %i[new create]
  resources :carts, only: %i[create update]
  resources :order_lines, only: %i[create destroy]
  resources :orders do
    put 'update_total', to: 'orders#update_total'
    resources :comments, only: %i[new create]
  end
  resources :products, only: %i[index show] do
    put 'like', to: 'products#like'
    put 'dislike', to: 'products#dislike'
    resources :comments, only: %i[new create]
  end
  devise_for :users
  resources :users, only: %i[index show] do
    resources :comments, only: %i[new create]
  end
  namespace :admin do
    get 'products/list', to: 'products#list'
    resources :products
    resources :product_logs, only: [:index]
    resources :users, only: %i[new create destroy]
    resources :comments, only: %i[index destroy update]
  end
end

app/models/user.rb
# frozen_string_literal: true

# Class for users
class User < ApplicationRecord
  include Discard::Model
  has_one :profile, dependent: :destroy
  has_many :product_logs
  has_many :orders
  has_many :comments, as: :commentable

  enum role: { admin: 0, support: 1, customer: 2 }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  delegate :full_name, :address, :phone, to: :profile

  # Override Devise's method to be unable the login and stop the session
  # of discarded users
  def active_for_authentication?
    super && !discarded?
  end

  # To integrate Doorkeeper with Devise 
  # we need a method to find user by email and password.
  class << self
    def authenticate(email, password)
      user = User.find_for_authentication(email: email)
      user.try(:valid_password?, password) ? user : nil
    end
  end
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

# Controller to register a user with his profile
class Admin::UsersController < ApplicationController
  include Errors

  def new
    authorize User
    @form = RegistrationForm.new
  end

  def create
    authorize User
    @form = RegistrationForm.new(registration_params.merge(user: current_user))
    if @form.save
      flash[:success] = 'User has been successfully created'
      redirect_to root_path
    else
      raise_exception(@form)
      render :new
    end
  end

  def destroy
    authorize User
    @form = User.find(params[:id])
    if @form.discard
      flash[:success] = 'User has been successfully removed'
    else
      raise_exception(@form)
    end
    redirect_to users_path
  end

  private

  def registration_params
    params.require(:registration_form).permit(:email, :password, :first_name, :last_name, :address, :phone, :role)
  end
end

app/controllers/api/v1/users_controller.rb
# frozen_string_literal: true

# Controller to show a user with his profile
class Api::V1::UsersController < Api::V1::ApiController
  before_action :doorkeeper_authorize!,
                only: %i[index show]
  def index
    @users = policy_scope(User)
    @users = UserRepresenter.for_collection.new(@users)
    render json: { users: @users }, status: :ok
  end

  def show
    @users = policy_scope(User)
    @user = @users.find(params[:id])
    @user = UserRepresenter.new(@user)
    render json: @user, status: :ok
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# Controller to show a user with his profile
class UsersController < ApplicationController
  include Comments
  def index
    @users = policy_scope(User)
  end

  def show
    @users = policy_scope(User)
    @form = @users.find(params[:id])
    display_comments_user(@form)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class="container">
  <div class="card col s6">
  <table class="responsive-table striped">
    <thead>
      <tr>
          <th>ID</th>
          <th>Full name</th>
          <th>Email</th>
          <th>Phone</th>
          <th>Role</th>
          <th>Details</th>
      </tr>
    </thead>

    <tbody>
    <% @users.each do |s| %>    
      <tr>
        <td><%= s.id%></td>
        <td><%= s.full_name%></td>
        <td><%= s.email%></td>
        <td><%= s.phone%></td>
        <td><%= s.role%></td>
        <td><%= link_to "Details", user_path(s.id) %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
  <div class="col s12">
    <h2 class="header"><%= @form.full_name%></h2>
    <div class="card horizontal">
      <div class="card-image">
        <img src="http://lorempixel.com/512/512/people/<%= rand(1..10)%>/">
      </div>
      <div class="card-stacked">
        <div class="card-content">
          <ul class="collection">
            <li class="collection-item">Email: <%= @form.email%></li>
            <li class="collection-item">Adress: <%= @form.address%></li>
            <li class="collection-item">Phone: <%= @form.phone%></li>
            <li class="collection-item">Role: <%= @form.role%></li>
          </ul>
        </div>
        <div class="card-action">
        <% if policy(@form).destroy? %>
          <%= link_to 'Delete User', admin_user_path, method: :delete, class: "btn waves-effect waves-light", data: { confirm: "Are you sure you want to delete this user?" } %> 
        <% end %>
        </div>
      </div>
    </div>
  </div>
  </div>
  <div class="row">

  <div id="commentable">

    <div class="container">
      <h4>Comments</h4>
      <%= render "comments/comments" %>
      <%= render "comments/comment" if user_signed_in?%>
    </div>
  </div>

  </div>

</div>