config/routes.rb
# frozen_string_literal: true

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => "/sidekiq"
  use_doorkeeper do
    skip_controllers :authorizations, :applications,
                     :authorized_applications
  end
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      get 'products/discarded', to: 'products#discarded'
      resources :products, except: %i[new edit] do
        put 'like', to: 'products#like'
        put 'dislike', to: 'products#dislike'
      end
      resources :orders, only: %i[index show]
      resources :carts, only: [:index], path: 'cart'
      resource :carts, except: %i[new edit show update] do
        put 'finalize', to: 'carts#finalize'
        put 'merge', to: 'carts#merge'
        patch 'discontinue', to: 'carts#discontinue'
        put 'update_line', to: 'carts#update_line'
        put 'delete_line', to: 'carts#delete_line'
      end
      resources :users, only: %i[index show]
      post 'users/password', to: 'passwords#create'
      put 'users/password', to: 'passwords#update'
    end
  end
  root to: 'products#index'
  resources :billing, only: %i[new create]
  resources :carts, only: %i[create update]
  resources :order_lines, only: %i[create destroy]
  resources :orders do
    put 'update_total', to: 'orders#update_total'
    resources :comments, only: %i[new create]
  end
  resources :products, only: %i[index show] do
    put 'like', to: 'products#like'
    put 'dislike', to: 'products#dislike'
    resources :comments, only: %i[new create]
  end
  devise_for :users
  resources :users, only: %i[index show] do
    resources :comments, only: %i[new create]
  end
  namespace :admin do
    get 'products/list', to: 'products#list'
    resources :products
    resources :product_logs, only: [:index]
    resources :users, only: %i[new create destroy]
    resources :comments, only: %i[index destroy update]
  end
end

app/views/shared/_flash.html.erb
<% if flash.any? %>
  <% flash.each do |alert, mssg| %>
    <div class="alert <%= alert %> card green lighten-4 green-text text-darken-4">
    <div class="card-content" id="my_alert">
      <p><i class="material-icons">check_circle</i>
      <span><%= alert.to_s.upcase %><br></span> <%= raw mssg.to_s %>
      <i class="material-icons right" onclick="document.getElementById('my_alert').style.display = 'none'">close</i></p>        
      </div>
    </div>
  <% end %>
<% end %>
<!--CUSTOM ALERTS COLOR CSS-->

app/views/shared/_footer.html.erb
<footer class="page-footer">  
  <div class="footer-copyright">
    <div class="container" style="text-align: center;">
    <% if user_signed_in? %>
    Logged in as <strong><%= current_user.email %></strong>
    <% else %>
    <strong>Ghost user<strong>
    <% end%>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
 
  <div class="nav-wrapper">
    <a href="<%= root_path%>" class="brand-logo">Snacks Store</a>
    <ul id="nav-mobile" class="right hide-on-med-and-down">      
      <li><a><%= link_to "Home", products_path %></a></li>
      <li><a><%= link_to "Cart", order_path(current_order.id ||= 0) %></a></li>
      <% if user_signed_in? %>
      <li><a><%= link_to "Purchased", orders_path %></a></li>
      <% if current_user.admin? %>
      <li>
        <a href="javascript:void(0)" class="dropdown-trigger" data-target="dropdown1">Product</a>
        <ul id='dropdown1' class='dropdown-content'>
          <li><%= link_to "Create", new_admin_product_path %></li>
          <li><%= link_to "Product Logs", admin_product_logs_path %></li>
          <li><%= link_to "Deleted", admin_products_list_path %></li>
        </ul>
      </li>
      <% end %>
      <li>
        <a href="javascript:void(0)" class="dropdown-trigger" data-target="dropdown2">Users</a>
        <ul id='dropdown2' class='dropdown-content'>
        <li><%= link_to "List", users_path %></li>
        <% unless current_user.customer? %>
          <li><%= link_to "Create", new_admin_user_path %></li>
          <li><%= link_to "Pending comments", admin_comments_path %></li>
        <% end %>
        </ul>
      </li>
      <li>|Session as <strong><%= current_user.role %></strong>|</li>
      <li><%= link_to 'Settings', edit_user_registration_path, :class => 'navbar-link' %></li>
      <li><a><%= link_to "Logout", destroy_user_session_path, method: :delete %></a></li>
      <% else %>
      <li>
      <li><a><%= link_to "Sign up", new_user_registration_path %></a></li>
      <li><a><%= link_to "Login", new_user_session_path %></a></li>
      </li>
      <% end %>
      
    </ul>
  </div>
</nav>

<script>
    var elems = document.querySelectorAll('.dropdown-trigger');
    var options = {
      hover: true,
      coverTrigger: false
    }
    var instances = M.Dropdown.init(elems,options);
</script>