config/routes.rb
# frozen_string_literal: true

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => "/sidekiq"
  use_doorkeeper do
    skip_controllers :authorizations, :applications,
                     :authorized_applications
  end
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      get 'products/discarded', to: 'products#discarded'
      resources :products, except: %i[new edit] do
        put 'like', to: 'products#like'
        put 'dislike', to: 'products#dislike'
      end
      resources :orders, only: %i[index show]
      resources :carts, only: [:index], path: 'cart'
      resource :carts, except: %i[new edit show update] do
        put 'finalize', to: 'carts#finalize'
        put 'merge', to: 'carts#merge'
        patch 'discontinue', to: 'carts#discontinue'
        put 'update_line', to: 'carts#update_line'
        put 'delete_line', to: 'carts#delete_line'
      end
      resources :users, only: %i[index show]
      post 'users/password', to: 'passwords#create'
      put 'users/password', to: 'passwords#update'
    end
  end
  root to: 'products#index'
  resources :billing, only: %i[new create]
  resources :carts, only: %i[create update]
  resources :order_lines, only: %i[create destroy]
  resources :orders do
    put 'update_total', to: 'orders#update_total'
    resources :comments, only: %i[new create]
  end
  resources :products, only: %i[index show] do
    put 'like', to: 'products#like'
    put 'dislike', to: 'products#dislike'
    resources :comments, only: %i[new create]
  end
  devise_for :users
  resources :users, only: %i[index show] do
    resources :comments, only: %i[new create]
  end
  namespace :admin do
    get 'products/list', to: 'products#list'
    resources :products
    resources :product_logs, only: [:index]
    resources :users, only: %i[new create destroy]
    resources :comments, only: %i[index destroy update]
  end
end

app/models/product.rb
# frozen_string_literal: true

# Class for product
class Product < ApplicationRecord
  include Discard::Model
  paginates_per 6
  acts_as_votable
  has_one_attached :image

  enum status: { active: 1, inactive: 0 }
  has_many :order_lines
  has_many :orders, through: :order_lines
  has_many :product_tags, dependent: :destroy
  has_many :tags, through: :product_tags
  has_many :product_logs
  has_many :comments, as: :commentable

  validates :sku, :name, uniqueness: true
  validates :name, :status, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0.0 }
  validates :stock, presence: true, numericality: { only_integer: true }
  validates :stock, inclusion: { in: 0..25, message: 'The value %{value} is not between in 0 and 25' }

  before_create :generate_sku

  def image_on_disk
    ActiveStorage::Blob.service.send(:path_for, image.key) if image.attached?
  end

  def generate_sku
    self.sku = SecureRandom.uuid
  end

  def avarage_rating
    (comments.sum(:rati) / comments.select(:rati).where('rati > 0').count).round(2)
  end

  def poor_stock?
    stock <= 3
  end

  def change_status
    inactive! if stock.zero?
  end

  scope :name_asc, -> { order(name: :asc) }

  # Callbacks of soft delete with Discard
  after_discard do
    comments.discard_all
  end

  after_undiscard do
    comments.undiscard_all
  end
end

app/controllers/admin/products_controller.rb
# frozen_string_literal: true

# class for CRUD product in Admin
class Admin::ProductsController < ApplicationController
  include Errors
  before_action :authenticate_user!
  before_action :load_product, only: %i[show edit]
  before_action :load_tags, only: %i[new create]

  def new
    authorize Product
    @product = Product.new
  end

  def create
    authorize Product
    @product = ProductCreator.call(product_params)
    raise_exception(@product) # Break exception
    flash[:success] = 'Product has been successfully created'
    redirect_to product_path(@product.id)
  end

  def update
    authorize Product
    @product = ProductUpdater.call(product_params, params[:id], current_user)
    raise_exception(@product)
    flash[:success] = 'Product has been successfully updated'
    redirect_to product_path(@product.id)
  end

  def destroy
    authorize Product
    @product = ProductDestroyer.call(params[:id])
    raise_exception(@product)
    flash[:success] = 'Product was succesfully removed'
    redirect_to root_path
  end

  def list
    @products = Product.discarded
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :price, :stock, :status, tag_ids: [])
  end

  def load_product
    @product = Product.find(params[:id])
    @tags = @product.tags
  end

  def load_tags
    @tags = Tag.all
  end
end

app/controllers/api/v1/products_controller.rb
# frozen_string_literal: true

# Class for ProductsController
class Api::V1::ProductsController < Api::V1::ApiController
  include MetaData
  before_action :doorkeeper_authorize!,
                only: %i[create update destroy discarded like dislike]

  before_action :found_product, only: %i[like dislike]

  def index
    @products = policy_scope(Product).page params[:page] # Policy_show products
    meta = meta_data(@products)
    @products = ProductSearcher.call(@products, search_params).page params[:page]
    @products = ProductRepresenter.for_collection.new(@products)
    render json: { products: @products, pagination_data: meta }, status: :ok
  end

  def show
    @products = policy_scope(Product)
    @product = @products.find(params[:id])
    @product = ProductRepresenter.new(@product)
    render json: @product, status: :ok
  end

  def create
    authorize Product
    @product = ProductCreator.call(product_params)
    @product = ProductRepresenter.new(@product)
    render json: @product, status: :ok
  end

  def update
    authorize Product
    @product = ProductUpdater.call(product_params, params[:id], current_user)
    @product = ProductRepresenter.new(@product)
    render json: @product, status: :ok
  end

  def destroy
    authorize Product
    @product = ProductDestroyer.call(params[:id])
    @product = ProductRepresenter.new(@product)
    render json: @product, status: :ok
  end

  def discarded
    authorize Product
    @products = Product.discarded
    @products = ProductRepresenter.for_collection.new(@products)
    render json: @products, status: :ok
  end

  def like
    @product.liked_by current_user
    @product = ProductRepresenter.new(@product)
    render json: @product, status: :ok
  end

  def dislike
    @product.disliked_by current_user
    @product = ProductRepresenter.new(@product)
    render json: @product, status: :ok
  end

  private

  def found_product
    @product = Product.active.find(params[:product_id])
  end

  def product_params
    params.require(:product).permit(:name, :description, :price, :stock, :status, tag_ids: [], image: {})
  end

  def search_params
    params.require(:search).permit(:name, :popularity, tag_ids: [])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include Comments
  include MetaData
  require 'pp'
  before_action :found_product, only: %i[like dislike]

  def index
    @products = policy_scope(Product).page params[:page] # Policy_show products
    meta = meta_data(@products)
    @products = ProductSearcher.call(@products, search_params).page params[:page]
    pp(@products)
  end

  def show
    @products = policy_scope(Product)
    @product = Product.find(params[:id])
    display_comments(@product)
  end

  def like
    @product.liked_by current_user
    render 'votable'
  end

  def dislike
    @product.disliked_by current_user
    render 'votable'
  end

  private

  def found_product
    @product = Product.find(params[:product_id])
  end

  def search_params
    params.fetch(:search, {}).permit(:name, :popu, tag_ids: [])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= form_for [:admin, @product], local: true, class: "col 12" do |f|%>
  <div class="row">
  </div>
  <div class="row">
    <div class="input-field col s12">
      <%= f.text_field :sku, disabled: true, class: :validate  %>
      <%= f.label :sku, 'SKU', class: @product.sku?.present? ? :active : ''  %>
    </div>
  </div>
  <div class="row">
    <div class="input-field col s12">
      <%= f.text_field :name, class: :validate  %>
      <%= f.label :name, 'Name', class: @product.name.present? ? :active : '' %>
    </div>
  </div>
  <div class="row">
    <div class="input-field col s12">
      <%= f.text_field :description, class: :validate  %>
      <%= f.label :description, 'Description', class: @product.description.present? ? :active : '' %>
    </div>
  </div>
  <div class="row">
    <div class="input-field col 6">
      <%= f.text_field :price, class: :validate, type: :number, min: 0.0, step: 0.01  %>
      <%= f.label :price, 'Price', class: :active %>
    </div>
  </div>
  <div class="row">
    <div class="input-field col 6">
      <%= f.text_field :stock, class: :validate, type: :number, min: 0  %>
      <%= f.label :stock, 'Stock', class: :active %>
    </div>
  </div>
  <div class="row">
    <div class="col s2">
      <label>STATUS:</label>
    </div>
    <div class="col s10">
      <div class="switch">
        <label>
          Inactive
          <%= f.check_box :status, {checked: @product.active? }, "active", "inactive" %>
          <span class="lever"></span>
          Active
        </label>
      </div>
    </div>
  </div>
  <div class="row"><h5>TAGS</h5> </div>
  <div class="row">

    <% Tag.all.each do |tag| %>    
    <label >
      <%= f.check_box :tag_ids, {multiple: true}, tag.id, nil%>
      <span style="margin-right: 50px;"><%= tag.name %></span>
    <label>    
    <% end %>

  </div>
  <div class="row"><!--Open div-->
  <div class="field col s6" style="text-align: right;">
      <%= f.submit class: "btn waves-effect waves-light" %>
  </div>
<%end%>

app/views/admin/products/edit.html.erb
<div class="container">
  <h1>Edit Product</h1>
  <div class="row">
    <%= render "form", tags: @tags %>
    <div class=" col s6", style="text-align: left;">
    <% if policy(@product).destroy? %>
    <%= link_to 'Delete Product', admin_product_path, method: :delete, class: "btn waves-effect waves-light", data: { confirm: "Are you sure you want to delete this product?" } %> 
    <% end %>
    </div>
    </div> <!--Close div inside of render form-->
  </div>
</div> 

app/views/admin/products/list.html.erb
<div class="container">
<h1>Products Discarded</h1>
  <div class="card col s6">
  <table>
    <thead>
      <tr>
          <th>SKU</th>
          <th>Name</th>
          <th>Description</th>
          <th>Price</th>
          <th>Stock</th>
          <th>Status</th>
          <th>Likes</th>
          <th>Dislikes</th>
          <th>Discarded at</th>
      </tr>
    </thead>

    <tbody>
    <% @products.each do |p| %>    

      <tr>
        <td><%= p.sku%></td>
        <td><%= p.name%></td>
        <td><%= p.description%></td>
        <td>$ <%= p.price%></td>
        <td><%= p.stock%></td>
        <td><%= p.status%></td>
        <td><%= p.cached_votes_up%></td>
        <td><%= p.cached_votes_down%></td>
        <td><%= p.discarded_at%></td>
      </tr>
      <tr>

    <% end %>

    </tbody>
  </table>
  </div>
</div>

app/views/admin/products/new.html.erb
<div class="container">
  <h1>New Product</h1>
  <div class="row">
  
    <%= render "form", tags: @tags %>
  
  </div>
</div>