config/routes.rb
# frozen_string_literal: true

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => "/sidekiq"
  use_doorkeeper do
    skip_controllers :authorizations, :applications,
                     :authorized_applications
  end
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      get 'products/discarded', to: 'products#discarded'
      resources :products, except: %i[new edit] do
        put 'like', to: 'products#like'
        put 'dislike', to: 'products#dislike'
      end
      resources :orders, only: %i[index show]
      resources :carts, only: [:index], path: 'cart'
      resource :carts, except: %i[new edit show update] do
        put 'finalize', to: 'carts#finalize'
        put 'merge', to: 'carts#merge'
        patch 'discontinue', to: 'carts#discontinue'
        put 'update_line', to: 'carts#update_line'
        put 'delete_line', to: 'carts#delete_line'
      end
      resources :users, only: %i[index show]
      post 'users/password', to: 'passwords#create'
      put 'users/password', to: 'passwords#update'
    end
  end
  root to: 'products#index'
  resources :billing, only: %i[new create]
  resources :carts, only: %i[create update]
  resources :order_lines, only: %i[create destroy]
  resources :orders do
    put 'update_total', to: 'orders#update_total'
    resources :comments, only: %i[new create]
  end
  resources :products, only: %i[index show] do
    put 'like', to: 'products#like'
    put 'dislike', to: 'products#dislike'
    resources :comments, only: %i[new create]
  end
  devise_for :users
  resources :users, only: %i[index show] do
    resources :comments, only: %i[new create]
  end
  namespace :admin do
    get 'products/list', to: 'products#list'
    resources :products
    resources :product_logs, only: [:index]
    resources :users, only: %i[new create destroy]
    resources :comments, only: %i[index destroy update]
  end
end

app/models/product.rb
# frozen_string_literal: true

# Class for product
class Product < ApplicationRecord
  include Discard::Model
  paginates_per 6
  acts_as_votable
  has_one_attached :image

  enum status: { active: 1, inactive: 0 }
  has_many :order_lines
  has_many :orders, through: :order_lines
  has_many :product_tags, dependent: :destroy
  has_many :tags, through: :product_tags
  has_many :product_logs
  has_many :comments, as: :commentable

  validates :sku, :name, uniqueness: true
  validates :name, :status, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0.0 }
  validates :stock, presence: true, numericality: { only_integer: true }
  validates :stock, inclusion: { in: 0..25, message: 'The value %{value} is not between in 0 and 25' }

  before_create :generate_sku

  def image_on_disk
    ActiveStorage::Blob.service.send(:path_for, image.key) if image.attached?
  end

  def generate_sku
    self.sku = SecureRandom.uuid
  end

  def avarage_rating
    (comments.sum(:rati) / comments.select(:rati).where('rati > 0').count).round(2)
  end

  def poor_stock?
    stock <= 3
  end

  def change_status
    inactive! if stock.zero?
  end

  scope :name_asc, -> { order(name: :asc) }

  # Callbacks of soft delete with Discard
  after_discard do
    comments.discard_all
  end

  after_undiscard do
    comments.undiscard_all
  end
end

app/controllers/admin/products_controller.rb
# frozen_string_literal: true

# class for CRUD product in Admin
class Admin::ProductsController < ApplicationController
  include Errors
  before_action :authenticate_user!
  before_action :load_product, only: %i[show edit]
  before_action :load_tags, only: %i[new create]

  def new
    authorize Product
    @product = Product.new
  end

  def create
    authorize Product
    @product = ProductCreator.call(product_params)
    raise_exception(@product) # Break exception
    flash[:success] = 'Product has been successfully created'
    redirect_to product_path(@product.id)
  end

  def update
    authorize Product
    @product = ProductUpdater.call(product_params, params[:id], current_user)
    raise_exception(@product)
    flash[:success] = 'Product has been successfully updated'
    redirect_to product_path(@product.id)
  end

  def destroy
    authorize Product
    @product = ProductDestroyer.call(params[:id])
    raise_exception(@product)
    flash[:success] = 'Product was succesfully removed'
    redirect_to root_path
  end

  def list
    @products = Product.discarded
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :price, :stock, :status, tag_ids: [])
  end

  def load_product
    @product = Product.find(params[:id])
    @tags = @product.tags
  end

  def load_tags
    @tags = Tag.all
  end
end

app/controllers/api/v1/products_controller.rb
# frozen_string_literal: true

# Class for ProductsController
class Api::V1::ProductsController < Api::V1::ApiController
  include MetaData
  before_action :doorkeeper_authorize!,
                only: %i[create update destroy discarded like dislike]

  before_action :found_product, only: %i[like dislike]

  def index
    @products = policy_scope(Product).page params[:page] # Policy_show products
    meta = meta_data(@products)
    @products = ProductSearcher.call(@products, search_params).page params[:page]
    @products = ProductRepresenter.for_collection.new(@products)
    render json: { products: @products, pagination_data: meta }, status: :ok
  end

  def show
    @products = policy_scope(Product)
    @product = @products.find(params[:id])
    @product = ProductRepresenter.new(@product)
    render json: @product, status: :ok
  end

  def create
    authorize Product
    @product = ProductCreator.call(product_params)
    @product = ProductRepresenter.new(@product)
    render json: @product, status: :ok
  end

  def update
    authorize Product
    @product = ProductUpdater.call(product_params, params[:id], current_user)
    @product = ProductRepresenter.new(@product)
    render json: @product, status: :ok
  end

  def destroy
    authorize Product
    @product = ProductDestroyer.call(params[:id])
    @product = ProductRepresenter.new(@product)
    render json: @product, status: :ok
  end

  def discarded
    authorize Product
    @products = Product.discarded
    @products = ProductRepresenter.for_collection.new(@products)
    render json: @products, status: :ok
  end

  def like
    @product.liked_by current_user
    @product = ProductRepresenter.new(@product)
    render json: @product, status: :ok
  end

  def dislike
    @product.disliked_by current_user
    @product = ProductRepresenter.new(@product)
    render json: @product, status: :ok
  end

  private

  def found_product
    @product = Product.active.find(params[:product_id])
  end

  def product_params
    params.require(:product).permit(:name, :description, :price, :stock, :status, tag_ids: [], image: {})
  end

  def search_params
    params.require(:search).permit(:name, :popularity, tag_ids: [])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include Comments
  include MetaData
  require 'pp'
  before_action :found_product, only: %i[like dislike]

  def index
    @products = policy_scope(Product).page params[:page] # Policy_show products
    meta = meta_data(@products)
    @products = ProductSearcher.call(@products, search_params).page params[:page]
    pp(@products)
  end

  def show
    @products = policy_scope(Product)
    @product = Product.find(params[:id])
    display_comments(@product)
  end

  def like
    @product.liked_by current_user
    render 'votable'
  end

  def dislike
    @product.disliked_by current_user
    render 'votable'
  end

  private

  def found_product
    @product = Product.find(params[:product_id])
  end

  def search_params
    params.fetch(:search, {}).permit(:name, :popu, tag_ids: [])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_grid.html.erb
<div class="container">
<div class="row">
<% @products.each do |product| %>   
  <div class="card col l4 m6 s12" style="min-height: 100px">
    <div class="card col-content">
      <div class="card-image waves-effect waves-block waves-light">
        <img class="activator">
        <!-- src="http://lorempixel.com/256/256/food/<%= rand(1..10)%>/" -->
      </div>
      <div class="card-content">
        <span class="card-title activator grey-text text-darken-4"><%=truncate(product.name, length: 30)%><i class="material-icons right">more_vert</i></span>
      </div>
      <div class="card-action">
      <div class="row">
        <div id="like">
        <p class="col s2"><label class="label-icon" for="thumb_up" id="likes_p<%= product.id %>">
        <%= link_to product_like_path(product.id), method: :put, remote: true, class: user_signed_in? ? '' : :disabled  do%>
          <i class="material-icons">thumb_up</i><span><%= product.cached_votes_up%></span>
        <% end %>
        </label></p>
        </div>
        <div id="dislike">
        <p class="col s2"><label class="label-icon" for="thumb_down" id="dislikes_p<%= product.id %>">
        <%= link_to product_dislike_path(product.id), method: :put, remote: true, class: user_signed_in? ? '' : :disabled  do%>
          <i class="material-icons">thumb_down</i><span><%= product.cached_votes_down%></span>
        <% end %>
        </label></p>
        </div>
        </div>
      <div class="row">
        <% if user_signed_in? && !current_user.customer? %>
        <%= link_to "Edit", edit_admin_product_path(product) %>
        <% end %>
        <%= link_to "Details", product_path(product.id) %>
        <% if product.active? %>
          <% if product.stock.positive? %>
          <%= form_with url: '/carts', scope: 'post' do |f|%>
            <%= f.hidden_field :product_id, value: product.id %>
            <%= f.submit 'Add to cart', class: "waves-effect waves-teal btn-flat"%>
          <% end %>
          <% end %>
        <% else %>
          <div style="width: 100%; height: 36px"></div>
        <% end %>
      </div>
      </div>
      <div class="card-reveal">
        <span class="card-title grey-text text-darken-4">Name: <%=product.name%><i class="material-icons right">close</i></span>
        <p>Price: <%= product.price%></p>
        <p>Stock: <%= product.stock%></p>
        <p>Description: <%= product.description%></p> 
      </div>
    </div>
  </div>
<% end %>
</div>
</div>

app/views/products/_search.html.erb
<div class="nav-wrapper">  
  <%= form_for :search, method: :get, remote: true do |f|%>
  <div class="row">
    <div class="col 8">     
      <div class="input-field">        
        <%= f.text_field :name, type: :search, id: :search_i, placeholder: 'Search' %>
        <label class="label-icon" for="search"><i class="material-icons">search</i></label>
        <i class="material-icons" onclick="document.getElementById('search_i').value = ''" >close</i>
      </div>
    </div>
    <div class="col 4">
      <% Tag.all.each do |tag| %>    
        <label >
          <%= f.check_box :tag_ids, {multiple: true}, tag.id, nil%>
          <span style="margin-right: 20px;"><%= tag.name %></span>
        <label>
      <% end %>
      <label >
          <%= f.check_box :popu %>
          <span style="margin-right: 20px;">Popularity</span>
        <label>
      <%= f.submit 'search', class: 'btn waves-effect waves-light' %>    
    </div>
  </div>
  <div class="row">    
  </div>
  <%end%>
</div>

app/views/products/index.html.erb
<div id="search">
<%= render partial: 'search' %>
</div>

<div id="grid">
    <%= render partial: "grid" %>
</div>

<!--PAGINATION-->
<div class="row"> 
<%= paginate @products, :params => {search: {name: (params[:search][:name] rescue nil)  }} %>
</div>

app/views/products/index.js.erb
(function init() {
  document.querySelector('#grid').innerHTML = '<%= escape_javascript(render(partial: "grid")) %>';
  //document.querySelector('#search').innerHTML = '<%= escape_javascript(render(partial: "search")) %>';
})()

app/views/products/show.html.erb
<div class="container">
  <div class="row">
  <div class="col s12">
    <h2 class="header"><%= @product.name%></h2>
    <div class="card horizontal">
      <div class="card-image">
        <img src="http://lorempixel.com/512/512/food/<%= rand(1..10)%>/">
      </div>
      <div class="card-stacked">
        <div class="card-content">
          <ul class="collection">
            <li class="collection-item">Sku: <%= @product.sku%></li>
            <li class="collection-item">Description: <%= @product.description%></li>
            <li class="collection-item">Price: $<%= @product.price%></li>
            <li class="collection-item">Stock: <%= @product.stock%></li>
            <li class="collection-item">Likes: <%= @product.cached_votes_up%></li>
            <li class="collection-item">Dislikes: <%= @product.cached_votes_down%></li>
            <li class="collection-item">Status: <%= @product.status%></li>
          </ul>
          <ul class="collection">
            <li class="collection-item">RATING: <%= @product.avarage_rating unless @product.avarage_rating.nan?%>
              <span><i class="material-icons" style="color: #26a69a;">grade</i></span>
            
            </li>
          </ul>
        </div>
        <div class="card-action">
          <a>
          <% if @product.active? %>
          <% if @product.stock.positive? %>
          <%= form_with url: '/carts', scope: 'post' do |f|%>
            <%= f.hidden_field :product_id, value: @product.id %>
            <%= f.submit 'Add to cart', class: "waves-effect waves-teal btn-flat"%>
          <% end %>
          <% end %>
        <% end %></a>
        </div>
      </div>
    </div>
  </div>
  </div>
  <div class="row">

  <div id="commentable"> 
    <div class="container">
      <h4>Comments</h4>
      <%= render "comments/comments" %>
      <%= render "comments/comment" if user_signed_in?%>
    </div>
  </div>

  </div>

</div>

app/views/products/votable.js.erb
(function init() {
  document.querySelector("#likes_p<%= @product.id %> span")
    .innerHTML = "<%= @product.get_likes.size %>";
  document.querySelector("#dislikes_p<%= @product.id %> span")
    .innerHTML = "<%= @product.get_dislikes.size %>";
})()